baseURL = "https://leopoldabgn.github.io/"
#languageCode = "fr-fr"
languageCode = "en-us"
title = "sl0wguy"
theme = "hugo-theme-console"

[params]
  brand = "user@ubuntu:~$"
  description = "Cybersecurity Enthusiast & CTF Player"
  animateStyle = "animate-fade-up"
  css = ["css/custom.css"]

[[params.navlinks]]
  name = "GitHub"
  url = "https://github.com/leopoldabgn"

[[params.navlinks]]
  name = "LinkedIn"
  url = "https://linkedin.com/in/labignoli"
