baseURL = "https://leopoldabgn.github.io/"
#languageCode = "fr-fr"
languageCode = "en-us"
title = "sl0wguy"
theme = "hugo-theme-console"

[params]
  brand = "user@ubuntu:~$"
  description = "Cybersecurity Enthusiast & CTF Player"
  animateStyle = "animate-fade-up"
  customCSS = ["css/custom.css"]

#[[params.navlinks]]
#  name = "GitHub"
#  url = "https://github.com/leopoldabgn"
#
#[[params.navlinks]]
#  name = "LinkedIn"
#  url = "https://linkedin.com/in/labignoli"

[[params.navlinks]]
  name = "OSCP+"
  url = "#certifications"

[[params.navlinks]]
  name = "Write-ups"
  url = "/writeups"

[[params.navlinks]]
  name = "AMSI Events"
  url = "#amsi-ctf-organization"

[[params.navlinks]]
  name = "CTFs"
  url = "#ctf-achievements"

[[params.navlinks]]
  name = "Projects"
  url = "#key-projects"

[[params.navlinks]]
  name = "Contact"
  url = "#contact"

